name: Deploy from Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code at specified tag
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Deploy Application
      run: |
        echo "Deploying code from tag: ${{ github.event.inputs.tag }}"
        ls -al
        # Replace below line with your real deployment script
        # ./deploy.sh or aws deploy, docker build, etc.
