name: Deploy from Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code at specified tag
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Show contents of text.txt
      run: |
        echo "Showing contents of text.txt from tag: ${{ github.event.inputs.tag }}"
        cat text.txt
